-- please add more to this if you think of any im out of ideas

HPJTTT = {
    chosen = 1,
    text = {
        "Also try Nubbys Number Factory!",
        "HotPot Edition",
        "Joker Poker",
        "The Original                                      Rougelike",
        "18+",
        "Plant Vs Faces",
        "how LOVELY",
        "guess you're really feeling the BALATRO",
        "Hey folks! In today's video we're back with another unseeded high score Balatro run. Here, after running a lot of Baron/Mime builds recently, I decided to work towards an Idol after receiving a lot of Queens and several Immolates in the early game. The result was one of the best Flush Five builds I've ever put together. Enjoy the video! ",
        "Ship It",
        "Go Next",
        "You should play Finity!",
        "You should play JoyousSpring!",
        "You should play Aikoyori's Shenanigans!",
        "You should play Paya's Terrible Additions!",
        "Nxkoo found dead in Miami",
        "Too many decks!",
        "Isn't this splash text from Potassium?",
        "Entropy did it!",
        "HE HAS A GUN",
        "My wife left me!",
        "Not sponsored!",
        "100% Unsatisfied!",
        "Still a better love story than Twilight!",
        "Still a better love story than Wedding Dash 3!",
        "Not compatible with Balamod!",
        "Fair and balanced!",
        "High quality video game!",
        "Rated E for Everyone!",
        "You know, for kids!",
        "What is Balatro",
        "I suppose, hey!",
        "Hi, TV Tropes!",
        "Mental breakdown in the Balatro modding channel?",
        "Electric boogaloo!",
        "YES SKIP TRAINING",
        "Now includes PhotoChad™",
        "After nine years in development, hopefully itll be worth the wait!",
        "Blue Stake, yet to be reworked.",
        "Featuring Dante from the Devil May Cry series",
        "New Funky Mode!",
        "Whose idea was this?!",
        "attempt to compare nil with number",
        "+1 Plasmid",
        "& Knuckles",
        "Numberslop!",
        "Only 20% cringe!",
        "Why are all my cards sliding around?",
        "Banned forever!",
        "All toasters toast toast!",
        "Skate2Win and MySpace are no match for me!",
        "Not funny, didn't laugh!",
        "There's so much OREO Chocolate Sandwich Cookies, 14.3oz!",
        "AGAIN!",
        "Let's take a look...",
        "Without the AI slop!",
        ">looks inside",
        "Friends of Jimbo Edition",
        "Great Value Blueberries",
        "Wordle in #general",
        "posted gore award",
        "now with big naturals",
        "DOES SENDING HTTP REQUEST COUNT AS FAIR GAME???",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "its peaj...",
        "Rocket, my beloved <3",
        "squid i am going to strap you to the back of the tsar bomba and email you to the nearest binary star system",
        "NOTHING !!!!",
    }
}



HPJTTT.chosen = (math.floor(os.time())%#HPJTTT.text)+1

HPJTTT.balala = (math.floor(os.time())%100) == 0