-- please add more to this if you think of any im out of ideas

if HPJTTT then return end

HPJTTT = {
    chosen = 1,
    text = {
        -- patch target
        "Also try Nubby's Number Factory!",
        "HotPot Edition",
        "Joker Poker",
        "The Original                                      Rougelike",
        "18+",
        "Plant Vs Faces",
        "how LOVELY",
        "guess you're really feeling the BALATRO",
        "Hey folks! In today's video we're back with another unseeded high score Balatro run. Here, after running a lot of Baron/Mime builds recently, I decided to work towards an Idol after receiving a lot of Queens and several Immolates in the early game. The result was one of the best Flush Five builds I've ever put together. Enjoy the video! ",
        "Ship It",
        "Go Next",
        "You should play Finity!",
        "You should play JoyousSpring!",
        "You should play Aikoyori's Shenanigans!",
        "You should play Paya's Terrible Additions!",
        "Nxkoo found dead in Miami",
        "Too many decks!",
        "Isn't this splash text from Potassium?",
        "Entropy did it!",
        "HE HAS A GUN",
        "My wife left me!",
        "Not sponsored!",
        "100% Unsatisfied!",
        "Still a better love story than Twilight!",
        "Still a better love story than Wedding Dash 3!",
        "Not compatible with Balamod!",
        "Fair and balanced!",
        "High quality video game!",
        "Rated E for Everyone!",
        "You know, for kids!",
        "What is Balatro",
        "I suppose, hey!",
        "Hi, TV Tropes!",
        "Mental breakdown in the Balatro modding channel?",
        "Electric boogaloo!",
        "YES SKIP TRAINING",
        "Now includes PhotoChad™",
        "After nine years in development, hopefully itll be worth the wait!",
        "Blue Stake, yet to be reworked.",
        "Featuring Dante from the Devil May Cry series",
        "New Funky Mode!",
        "Whose idea was this?!",
        "attempt to compare nil with number",
        "+1 Plasmid",
        "& Knuckles",
        "Numberslop!",
        "Only 20% cringe!",
        "Why are all my cards sliding around?",
        "Banned forever!",
        "All toasters toast toast!",
        "Skate2Win and MySpace are no match for me!",
        "Not funny, didn't laugh!",
        "There's so much OREO Chocolate Sandwich Cookies, 14.3oz!",
        "AGAIN!",
        "Let's take a look...",
        "Without the AI slop!",
        ">looks inside",
        "Friends of Jimbo Edition",
        "Great Value Blueberries",
        "Wordle in #general",
        "posted gore award",
        "now with big naturals",
        "DOES SENDING HTTP REQUEST COUNT AS FAIR GAME???",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "its peaj...",
        "Rocket, my beloved <3",
        "squid i am going to strap you to the back of the tsar bomba and email you to the nearest binary star system",
        "NOTHING !!!!",
        "The Original And The Best",
        "Brought to you by Entropy Casinos",
        "The Ride",
        "The Movie",
        "The Game",
        "The Movie: The Game",
        "Help! I'm stuck in a window title factory!",
        "Double Dash!!",
        "I can't read, I'm a Balatro fan!",
        "The Flamethrower (this one's popular with the kids)",
        "Oh god, oh god help me",
        "Featuring Dante from the Devil May Cry series (again)",
        "Patent Pending",
        "Sega Does What Nintendon't",
        "Nintendoes what Genesisn't",
        "Aiyoriok Shimigimas",
        "Playbook Tomorrow",
        "Ortalab Tomorrow",
        "guys i have a legit copy of winrar",
        "Mental breakdown in Cryptid VC",
        "guyse pauseth for a secondth",
        "so i haveth a laser pointere",
        "now with 100% more plinko",
        "Also try Terraria?",
        "iroyokia is FUCKING dead",
        "Playbook tomorrow <Again!>",
        "'guys why is my Cryptic mod crashing'",
        "Also try Portal 2 Authoring Tools!",
        "missingno",
        "§7hi guys",
        "Jokes on you, dumbass. The chicken is ghost too",
        "With 100% less Herobrine!",
        "Don't Google Translate 'keys cow' in Filipino",
        "Absolutely no alcohol*",
        "Held together with hopes and ~~dreams~~ memes",
        "j",
        "guys i really did buy FL Studio",
        "https://open.spotify.com/track/4QJndoYmN9io3P7l3dAGyt",
        "post this if you sleep like this",
        "find h3nce find peace",
        "can I get uhhhhhhhhh",
        "George, the evil and intimidating horse",
        "big mac and a large fries",
        "punching grandmas 🤜 👵",
        "nxgoon, the \"aro-ace\"", -- wtf nxkoo why are you like this
        "Update your Steamodded",
        "Compatible with Windows, macOS, and Linux!",
        "why is my patch not working",
        "the second currency has hit the hot pot",
        "+4 Mult",
        ":blunder:",
        "Imagine knowing what you are doing",
        "May the Soul be in Arcana Pack",
        "Speed, Power, Stamina",
        "attempt to compare number with table",
        "WDYM NO LABUBU GLASS BRIDGE",
        "Code my Jokers",
        "obelisk.",
        "when the lightner is sus",
        "super idol de xiao rong",
        "xue hua piao piao bei feng xiao xiao",
        "This sentence IS false! (don't think about it)",
        "jtem added 3 jokers :fire:",
        "Discord Certified Porch Pirates",
        "How Handy!",
        "how do i code a joker asked no one ever",
        "fix: it was never broken but idk",
        "umpo ap!sdn s! -|-xa-|- s!y_|_",
        "I donated to The Trevor Project!",
        "among us",
        "okay seriously can someone qc this mod",
        "Pretty Clownery",
        "Spades of the Wild",
        "Crashers",
        "the Rock!",
        "Now with at least 1 jokers!",
        "deez nuts",
        "Game of the Year Edition",
        "A Telltale Games Series",
        "The Order of the Stone",
        "with 100% more shops",
        "It's about time!",
        "Farming commits",
        "Play Fool's Gambit!",
        "HPJTTT.text[#HPJTTT.text+1] = \"insert joke here\"",
        "\"what do you mean we ran out of ideas, we cant r- oh.\"",
        "Play [REDACTED].",
        "var titleText = \"Play Word Bomb!\"",
        "for (var i = 0; i < array_length(HPJTTT.text); i++){show_debug_message(\"Fuck\")}",
        "Adversaries Purified."
    }
}



HPJTTT.chosen = (math.floor(os.time())%#HPJTTT.text)+1

HPJTTT.balala = (math.floor(os.time())%100) == 0