-- please add more to this if you think of any im out of ideas

if HPJTTT then return end

HPJTTT = {
    chosen = 1,
    text = {
        -- patch target
        "Also try Nubby's Number Factory!",
        "HotPot Edition",
        "Joker Poker",
        "The Original                                      Rougelike",
        "18+",
        "Plant Vs Faces",
        "how LOVELY",
        "guess you're really feeling the BALATRO",
        "Hey folks! In today's video we're back with another unseeded high score Balatro run. Here, after running a lot of Baron/Mime builds recently, I decided to work towards an Idol after receiving a lot of Queens and several Immolates in the early game. The result was one of the best Flush Five builds I've ever put together. Enjoy the video! ",
        "Ship It",
        "Go Next",
        "You should play Finity!",
        "You should play JoyousSpring!",
        "You should play Aikoyori's Shenanigans!",
        "You should play Paya's Terrible Additions!",
        "You should play Phanta!",
        "You should play BFDI!",
        "You should play Catan!",
        "You should play Tonsmith!",
        "You should play Fool's Gambit!",
        "You should play Revo's Vault!",
        "You should play Alloy!",
        "You should use Photon Mod Manager!",
        "You should play An Atture Asorment!",
        "You should play Judgement!",
        "You should play [INSERT SELF PLUG HERE]!",
        "You should play Balatro!",
        "Nxkoo found dead in Miami",
        "Too many decks!",
        "Isn't this splash text from Potassium?",
        "Entropy did it!",
        "HE HAS A GUN",
        "My wife left me!",
        "Not sponsored!",
        "100% Unsatisfied!",
        "Still a better love story than Twilight!",
        "Still a better love story than Wedding Dash 3!",
        "Not compatible with Balamod!",
        "Fair and balanced!",
        "High quality video game!",
        "Rated E for Everyone!",
        "You know, for kids!",
        "What is Balatro",
        "I suppose, hey!",
        "Hi, TV Tropes!",
        "Mental breakdown in the Balatro modding channel?",
        "Electric boogaloo!",
        "YES SKIP TRAINING",
        "Now includes PhotoChad™",
        "After nine years in development, hopefully itll be worth the wait!",
        "Blue Stake, yet to be reworked.",
        "Featuring Dante from the Devil May Cry series",
        "New Funky Mode!",
        "Whose idea was this?!",
        "attempt to compare nil with number",
        "+1 Plasmid",
        "& Knuckles",
        "Numberslop!",
        "Only 20% cringe!",
        "Why are all my cards sliding around?",
        "Banned forever!",
        "All toasters toast toast!",
        "Skate2Win and MySpace are no match for me!",
        "Not funny, didn't laugh!",
        "There's so much OREO Chocolate Sandwich Cookies, 14.3oz!",
        "AGAIN!",
        "Let's take a look...",
        "Without the AI slop!",
        ">looks inside",
        "Friends of Jimbo Edition",
        "Great Value Blueberries",
        "Wordle in #general",
        "posted gore award",
        "now with big naturals",
        "DOES SENDING HTTP REQUEST COUNT AS FAIR GAME???",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "its peaj...",
        "Rocket, my beloved <3",
        "squid i am going to strap you to the back of the tsar bomba and email you to the nearest binary star system",
        "NOTHING !!!!",
        "The Original And The Best",
        "Brought to you by Entropy Casinos",
        "The Ride",
        "The Movie",
        "The Game",
        "The Movie: The Game",
        "Help! I'm stuck in a window title factory!",
        "Double Dash!!",
        "I can't read, I'm a Balatro fan!",
        "The Flamethrower (this one's popular with the kids)",
        "Oh god, oh god help me",
        "Featuring Dante from the Devil May Cry series (again)",
        "Patent Pending",
        "Sega Does What Nintendon't",
        "Nintendoes what Genesisn't",
        "Aiyoriok Shimigimas",
        "Playbook Tomorrow",
        "Ortalab Tomorrow",
        "guys i have a legit copy of winrar",
        "Mental breakdown in Cryptid VC",
        "guyse pauseth for a secondth",
        "so i haveth a laser pointere",
        "now with 100% more plinko",
        "Also try Terraria?",
        "iroyokia is FUCKING dead",
        "Playbook tomorrow <Again!>",
        "'guys why is my Cryptic mod crashing'",
        "Also try Portal 2 Authoring Tools!",
        "missingno",
        "§7hi guys",
        "Jokes on you, dumbass. The chicken is ghost too",
        "With 100% less Herobrine!",
        "Don't Google Translate 'keys cow' in Filipino",
        "Absolutely no alcohol*",
        "Held together with hopes and ~~dreams~~ memes",
        "j",
        "guys i really did buy FL Studio",
        "https://open.spotify.com/track/4QJndoYmN9io3P7l3dAGyt",
        "post this if you sleep like this",
        "find h3nce find peace",
        "can I get uhhhhhhhhh",
        "George, the evil and intimidating horse",
        "big mac and a large fries",
        "punching grandmas 🤜 👵",
        "nxgoon, the \"aro-ace\"", -- wtf nxkoo why are you like this
        "Update your Steamodded",
        "Compatible with Windows, macOS, and Linux!",
        "why is my patch not working",
        "the second currency has hit the hot pot",
        "+4 Mult",
        ":blunder:",
        "Imagine knowing what you are doing",
        "May the Soul be in Arcana Pack",
        "Speed, Power, Stamina",
        "attempt to compare number with table",
        "WDYM NO LABUBU GLASS BRIDGE",
        "Code my Jokers",
        "obelisk.",
        "when the lightner is sus",
        "super idol de xiao rong",
        "xue hua piao piao bei feng xiao xiao",
        "This sentence IS false! (don't think about it)",
        "jtem added 3 jokers :fire:",
        "Discord Certified Porch Pirates",
        "How Handy!",
        "how do i code a joker asked no one ever",
        "fix: it was never broken but idk",
        "umpo ap!sdn s! -|-xa-|- s!y_|_",
        "I donated to The Trevor Project!",
        "among us",
        "okay seriously can someone qc this mod",
        "Pretty Clownery",
        "Spades of the Wild",
        "Crashers",
        "the Rock!",
        "Now with at least 1 jokers!",
        "deez nuts",
        "Game of the Year Edition",
        "A Telltale Games Series",
        "The Order of the Stone",
        "with 100% more shops",
        "It's about time!",
        "Farming commits",
        "It's dead, it's disgusting, it's Photochad.",
        "aeiou",
        "What the? You gotta be kidding me.",
        "I can teach you how to move!",
        "Don't let the enemy freak you out!",
        "Nice moves, maverick!",
        "As bugless as a restaurant is flyless!",
        "la li lu le lo",
        ":3",
        "but beats 2 and 4 are swapped",
        "but every time they say \"Balatro\" it goes back to the start",
        "but the game changes every time they click",
        "but it's Google translated 39 times",
        "Lua! Because why not!",
        "Alan please add details",
        "Just between you and me, Plincoins are actually just Pesos.",
        "Live, Laugh, Lose",
        "Pregnant Sims can no longer brawl.",
        "Man. Talis Man.",
        "Ah, Superintendent Chalmers, welcome!",
        "If this is not you, click here.",
        "But Stanley simply couldn't handle the pressure.",
        "Oh wait, what's this? Wait wait wait, wait, it's- This is all wrong, this isn't the Stanley Parable!",
        "2",
        "88888888",
        "I will make hat from you, little bunny.",
        "ooooooOOOOOOOOOOoooooooo...",
        "You'd be surprised how much I got paid to make these flavour texts!",
        "Is this just fantasy?",
        "GALILEO! galileo! GALILEO! galileo! Galileo Figaro!",
        "- .... . / .-.. --- -. --. / .- -. -.. / ... .... --- .-. - / --- ..-. / .. - -.-.--",
        "King Dragon sends his regards.",
        "0800303 30080 883 003 3 08 3 8 8 8 3 0 038",
        "Play Fool's Gambit!",
        "HPJTTT.text[#HPJTTT.text+1] = \"insert joke here\"",
        "\"what do you mean we ran out of ideas, we cant r- oh.\"",
        "Play [REDACTED].",
        "var titleText = \"Play Word Bomb!\"",
        "for (var i = 0; i < array_length(HPJTTT.text); i++){show_debug_message(\"Fuck\")}",
        "Adversaries Purified.",
        "... and some other fucking actors",
        "and Knuckles",
        "Meow!",
        "Meowww!",
        "Nya!",
        "Nyaaa!",
        "Do not the cat",
        "Nothing built can last forever. And every legend, no matter how great, fades with time. With each passing year, more and more details are lost... until all that remains are myths. Half truths. To put it simply, lies. And yet in all the known universe, between here and the Far Lands, the legend of the Order of the Stone endures, unabridged, as self-evident fact. Indeed, it is only a troubled land that has need for heroes - and ours was fortunate to have, so long ago, four heroes such as these: Gabriel the Warrior, before whose sword all combatants would tremble. Ellegaard the Redstone Engineer, whose machines would spark an era of invention. Magnus the Rogue, who would channel his destructive creativity for the benefit of all. And Soren the Architect, Builder of Worlds and leader of the Order of the Stone. These FOUR friends together, would give so much to gain their rightful place as FOUR heroes. Their greatest quest would take them on a dangerous journey to fight a mysterious creature known as the Ender Dragon. In the end, the Order of the Stone emerged victorious and the dragon was defeated. Their story complete, they slipped away into the pages of legends.",
        "WOOOOOOOW WOOOOOOOOOOOOOOOOOW WOOOOOOOOOOOOOOOOOW dibit dioot TBTBWOOOOOOOWTBTBT WOOOOOOOOOOOOOOOOOW TBTBWOOOOOOOOOOOOOOOOOWTBBTBT dibit dioodDOOOT doooot wAAAAAAAAAAAAAA Balala booT but but BAP but ba dooooot WAAAAAAAAAAAAAAAAAAAAAAAA dadut doot doot bung Bap bop bap cwhAAAAAAAAAAAAAAAAA dOoaCHA doot Cha t chat cht cht AAAAEDJ DOot chchct doot do DADut bung chthhctbapchbopchbap DUbudu wowowowowowowoWOWOWOWOWOWOWOWOWOWWWwwuwuuwuuwuwuuuuuuuuwuwuw wwwwwwwwwwwwwwwWOWOWOWOOWOWOWOWOWOWOW DABADABAdabdbabdbadbb wowowowowooOWOWOWOWOWOOWOWOWmmmmmmWOWOWOWOOOWm m mm m m m mm m wa wa wa wa wa doot OWOWOOWOWOWOOWOWOO WOOWOWOWOWOOWOWdot WOWOWOWOWOWOWWOWOWOWOWOW DABABABABABABBAbabBAbabbababab mmmWOWOWOWOWOWOOWOWOWOWOWooooooo oo o oWOwowowooWuWUwuwuuuuuuuuuuuuuRrrrrrrrrrrrrrrrrrrrrrrrr wa wa wa wa wa dot WAAAAAAAAAAAAAAAAAAAAAAAAAA dabadadot BAP bop cht cht mMMmmmmm WAAAAAAAAAAAAAAAAAAAAAAAA dopapotad dada bmtp BAP DADadoDAHhhh WOOOOOOOOOOOOOOOOOOOOOOOOW DOO ODPOD WOOOOOOOOOOOOOOOOOOOOW ODODPOD WOOOOOOOOOOOOOOOOOOOOOW bum bum DABOtDat bum mmaemmfmm bmmmm baaaagagagggg ccc ctcttc bap bop dit dot shhhwwwwwwwwWWWWWWW WOOOOOOOW WOOOOOOOOOOOOOOOOOW WOOOOOOOOOOOOOOOOOW dibit dioot TBTBWOOOOOOOWTBTBT WOOOOOOOOOOOOOOOOOW TBTBWOOOOOOOOOOOOOOOOOWTBBTBT dibit dioodDOOOT doooot wAAAAAAAAAAAAAA Balala booT but but BAP but ba dooooot WAAAAAAAAAAAAAAAAAAAAAAAA dadut doot doot bung Bap bop bap cwhAAAAAAAAAAAAAAAAA dOoaCHA doot Cha t chat cht cht AAAAEDJ DOot chchct doot do DADut bung chthhctbapchbopchbap DUbudu wowowowowowowoWOWOWOWOWOWOWOWOWOWWWwwuwuuwuuwuwuuuuuuuuwuwuw wwwwwwwwwwwwwwwWOWOWOWOOWOWOWOWOWOWOW DABADABAdabdbabdbadbb wowowowowooOWOWOWOWOWOOWOWOWmmmmmmWOWOWOWOOOWm m mm m m m mm m wa wa wa wa wa doot OWOWOOWOWOWOOWOWOO WOOWOWOWOWOOWOWdot WOWOWOWOWOWOWWOWOWOWOWOW DABABABABABABBAbabBAbabbababab mmmWOWOWOWOWOWOOWOWOWOWOWooooooo oo o oWOwowowooWuWUwuwuuuuuuuuuuuuuRrrrrrrrrrrrrrrrrrrrrrrrr wa wa wa wa wa dot WAAAAAAAAAAAAAAAAAAAAAAAAAA dabadadot BAP bop cht cht mMMmmmmm WAAAAAAAAAAAAAAAAAAAAAAAA dopapotad dada bmtp BAP DADadoDAHhhh WOOOOOOOOOOOOOOOOOOOOOOOOW DOO ODPOD WOOOOOOOOOOOOOOOOOOOOW ODODPOD WOOOOOOOOOOOOOOOOOOOOOW bum bum DABOtDat bum mmaemmfmm bmmmm baaaagagagggg ccc ctcttc bap bop dit dot shhhwwwwwwwwWWWWWWW",
        "THE MOON!",
        "The Hottest Potato",
        "and now... a word from our Sponsor. Entropy.",
        "Attempt to compare Joker with Table",
        "Now in 3D",
        TMJ and "Thanks for using Too Many Jokers! ~ cg" or "Use Too Many Jokers! ~ cg", --tmj prio is lower - this wont load anymore (context: used to be in a diff file loaded normally)
        "Cassoosted Fuper",
        "Splipped Droost",
        "mb6fbhsphdrcb",
        "Spinner Stunning",
        "JTA",
        "Bubsdrop",
        "BIS",
        "Backboost",
        "silly ahh drivables - @lily.felli",
        "130 lbs",
        "Niko: She's 10. Can I Mate?",
        CardPronouns and "This is so woke!" or "Uhh.... install CardPronouns!", --cprns prio is  literally -99 million :3 - this wont load anymore
        "awawa awebo",
        "I wish shadows had rights",
        "The cat atop the far tree whispers sweet promises to passerbys",
        "I think we should stop having money. That sounds like a good thing.",
        "One or two extra currencies",
        "Shoutouts to gay foxgirls",
        "In a Cargo Box?",
        "Two Hotties, One potato.",
        "-- TODO: your mom",
        Entropy and "You are not immune to Propaganda" or "generic message", --holes bad?
        "The Oldest Anarchy Mod In Balatro",
        "D1D7",
        "smots gaming",
        "Tip number 10: Sit at the chessboard and play with yourself",
        "Murph will do anything but wheel of mods",
        "Grows offline!",
        "Restraining Order means nothing to me",
        "Why so serious?",
        "Why so genius?",
        CardPronouns and "Why so queerious?" or "generic message",
        "MEDIC!",
        "REF DO SOMETHING",
        "77 + 33 = 100",
        "Are you guys going trick or treating?",
        "I'm sorry, but as an AI language model, I don't have consciousness or self-awareness. I'm simply a program designed to process and generate human-like text.",
        "In case of an investigation by any federal entity or similar, I do not have any involvement with this group or with the people in it, I do not know how I am here, probably added by a thrid party, I do not support any actions by the member of this group.",
        "Now gluten-free!",
        "THEIR PRONOUNS ARE THEY/THE",
        "m",
        "Made by: The F@#! Squad",
        "It's never Lupus.",
        "THIS IS SPARTA!",
        "I got freaked",
        "Oh my god bruh",
        "Okie-dokie Artichokie!",
        "Numberslop in MY Balatro Mod?! There's more likely than what you think!",
        "GAY EDITION",
        "Now compatible with Birthlatro!",
        "What the dog doin?",
        "Nerf what if there was a joker",
        "*notices bulge* OwO What's this?",
        "Now with no preservatives or artificial sweeteners",
        "Woof",
        "Todays random seed is: "..tostring(math.floor(os.time()) % 100),
        "Merge branch 'main' of https://github.com/the-Astra/Hot-Potato"
    }
}



HPJTTT.chosen = (math.floor(os.time()) % #HPJTTT.text) + 1

HPJTTT.balala = (math.floor(os.time()) % 100) == 0
